//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSu
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayDauGia { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string TenDonViSD { get; set; }
        public Nullable<int> IDTTCB { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ThongTinCB ThongTinCB { get; set; }
    }
}
