//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinCB()
        {
            this.LichSus = new HashSet<LichSu>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Loai { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public string TenDonViCQ { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSu> LichSus { get; set; }
    }
}
