//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int ID { get; set; }
        public Nullable<int> Users_ID { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
    
        public virtual User User { get; set; }
    }
}
